# Generated by Django 3.2 on 2021-05-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_body',
            new_name='review_content',
        ),
    ]
