# Generated by Django 3.2 on 2021-05-14 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20210514_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_content',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
