# Generated by Django 3.2 on 2021-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourites',
        ),
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
