# Generated by Django 3.2 on 2021-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
