# Generated by Django 3.2 on 2021-05-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_review_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
